apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f kompose-docker.yml -o kubernetes/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: nginx-thrift
  name: nginx-thrift
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    io.kompose.service: nginx-thrift
