apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f kompose-docker.yml -o kubernetes/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: url-shorten-memcached
  name: url-shorten-memcached
spec:
  ports:
    - name: "11211"
      port: 11211
      targetPort: 11211
  selector:
    io.kompose.service: url-shorten-memcached
