apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-kompose.yml -o kubernetes/ -n media
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: jaeger
  name: jaeger
  namespace: media
spec:
  ports:
    - name: "16686"
      port: 16686
      targetPort: 16686
  selector:
    io.kompose.service: jaeger
