apiVersion: v1
data:
  nginx.conf: "# Load the OpenTracing dynamic module.\nload_module modules/ngx_http_opentracing_module.so;\n\n#
    Checklist: Make sure that worker_processes == #cores you gave to\n# nginx process\nworker_processes
    \ 4;\n\n# error_log  logs/error.log;\n\n# Checklist: Make sure that worker_connections
    * worker_processes\n# is greater than the total connections between the client
    and Nginx. \nevents {\n  worker_connections  1024;\n}\n\nerror_log  logs/error.log;\n\nenv
    fqdn_suffix;\n\nhttp {\n  # Load a vendor tracer\n  opentracing on;\n  opentracing_load_tracer
    /usr/local/lib/libjaegertracing_plugin.so /usr/local/openresty/nginx/jaeger-config.json;\n\n
    \ include       mime.types;\n  default_type  application/octet-stream;\n\n  log_format
    main '$remote_addr - $remote_user [$time_local] \"$request\"'\n                  '$status
    $body_bytes_sent \"$http_referer\" '\n                  '\"$http_user_agent\"
    \"$http_x_forwarded_for\"';\n  # access_log  logs/access.log  main;\n\n  sendfile
    \       on;\n  tcp_nopush      on;\n  tcp_nodelay     on;\n\n  # Checklist: Make
    sure the keepalive_timeout is greateer than\n  # the duration of your experiment
    and keepalive_requests\n  # is greateer than the total number of requests sent
    from\n  # the workload generator\n  keepalive_timeout  120s;\n  keepalive_requests
    100000;\n\n  # Docker default hostname resolver\n  #resolver 127.0.0.11 ipv6=off;\n
    \ resolver kube-dns.kube-system.svc.cluster.local ipv6=off valid=10s;\n\n  lua_package_path
    '/usr/local/openresty/nginx/lua-scripts/?.lua;;';\n\n  server {\n\n    # Checklist:
    Set up the port that nginx listens to.\n    listen       8080 reuseport;\n    server_name
    \ localhost;\n\n    # Checklist: Turn of the access_log and error_log if you\n
    \   # don't need them.\n    access_log  off;\n    # error_log off;\n\n    lua_need_request_body
    on;\n\n    # Checklist: Make sure that the location here is consistent\n    #
    with the location you specified in wrk2.\n    location /wrk2-api/user/register
    {\n      content_by_lua '\n          local client = require \"wrk2-api/user/register\"\n
    \         client.RegisterUser();\n      ';\n    }\n\n    location /wrk2-api/movie/register
    {\n      content_by_lua '\n          local client = require \"wrk2-api/movie/register\"\n
    \         client.RegisterMovie();\n      ';\n    }\n\n    location /wrk2-api/review/compose
    {\n      content_by_lua '\n          local client = require \"wrk2-api/review/compose\"\n
    \         client.ComposeReview();\n      ';\n    }\n\n    location /wrk2-api/movie-info/write
    {\n      content_by_lua '\n          local client = require \"wrk2-api/movie-info/write\"\n
    \         client.WriteMovieInfo();\n      ';\n    }\n\n    location /wrk2-api/cast-info/write
    {\n      content_by_lua '\n          local client = require \"wrk2-api/cast-info/write\"\n
    \         client.WriteCastInfo();\n      ';\n    }\n\n    location /wrk2-api/plot/write
    {\n      content_by_lua '\n          local client = require \"wrk2-api/plot/write\"\n
    \         client.WritePlot();\n      ';\n    }\n  }\n}\n"
kind: ConfigMap
metadata:
  name: nginx-web-server-cm1
