apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-kompose.yml -o kubernetes/ -n media
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: nginx-web-server
  name: nginx-web-server
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-web-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-kompose.yml -o kubernetes/ -n media
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: nginx-web-server
    spec:
      containers:
        - image: yg397/openresty-thrift:xenial
          name: nginx-web-server
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: fqdn_suffix
              value: ".media.svc.cluster.local"
          volumeMounts:
            #- mountPath: /usr/local/openresty/nginx/lua-scripts
            #  name: nginx-web-server-cm0
            - mountPath: /usr/local/openresty/nginx/lua-scripts
              name: lua-scripts
                #- mountPath: /usr/local/openresty/nginx/conf/nginx.conf
                #  name: nginx-web-server-cm1
                #  subPath: nginx.conf
            - mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              name: nginx-config
            - mountPath: /usr/local/openresty/nginx/jaeger-config.json
              name: nginx-web-server-cm2
              subPath: jaeger-config.json
            - mountPath: /gen-lua
              name: nginx-web-server-cm3
      hostname: nginx-thrift
      restartPolicy: Always
      volumes:
        - name: lua-scripts
          hostPath:
            path: /home/taylor/DeathStarBench/mediaMicroservices/nginx-web-server/lua-scripts
            type: Directory
        - name: nginx-config
          hostPath:
            path: /home/taylor/DeathStarBench/mediaMicroservices/nginx-web-server/conf/nginx.conf
            type: File
              #- configMap:
              #    items:
              #      - key: nginx.conf
              #        path: nginx.conf
              #    name: nginx-web-server-cm1
              #  name: nginx-web-server-cm1
        - configMap:
            items:
              - key: jaeger-config.json
                path: jaeger-config.json
            name: nginx-web-server-cm2
          name: nginx-web-server-cm2
        - configMap:
            name: nginx-web-server-cm3
          name: nginx-web-server-cm3
